"""Update IDs to use PostgreSQL UUID type

Revision ID: 4eb27bb9d58b
Revises: 1c21530f63b1
Create Date: 2025-06-14 16:32:46.094246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb27bb9d58b'
down_revision: Union[str, None] = '1c21530f63b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
