"""add date and timestamps to exercise logs

Revision ID: beca26b5f906
Revises: c66c0a9f2189
Create Date: 2025-06-23 22:51:20.315425

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beca26b5f906'
down_revision: str | None = 'c66c0a9f2189'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_logs', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('exercise_logs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('exercise_logs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_logs', 'updated_at')
    op.drop_column('exercise_logs', 'created_at')
    op.drop_column('exercise_logs', 'date')
    # ### end Alembic commands ###
